### ISSUE TITLE
netPI-netx-programming-examples doesn´t woks with Modbus Slave simulator

### ISSUE THREAD

**Issue by engluciana** [Hilscher/netPI-netx-programming-examples#3]
I had install the netPI-netx-programming-examples in NETPI according instructions from Docker Hub Documentation.  In the PacketHandlerOMB.c I put in STATIC IP the IP of Modbus Slave simulator. After this, I  complile using the make and any errors occurs. After  I run using the command sudo ./OMB_simpleConfig. The programs runs but doens't connect in Modbus Slave simulator.  I read manual of Protocol API Open Modbus/TCP but I don´t undertand because is very confusing. I need help to undertand how to make to configuring the Modbus.

**Comment by hilschernetpi** [comment]
hi there, I want to highlight at this point that the example provided in the netPI-netx-programming example configures the netPI as Modbus Slave. So if you say you are using a modbus slave simulator the same time then this does not fit together. You need a Modbus TCP client software to connect to netPI

**Comment by hilschernetpi** [comment]
What I am using personally since 20 years is a Window program call "Modbus Poll" from here https://www.modbustools.com/download.html which is a modbus master/client. It runs for a while and then stops if no licenses has been bought. But for a test it is good enough.

**Comment by engluciana** [comment]
Thanks for help me.
